version: "3"

services:
        db:
                image: mysql:8.0.33
                command: --default-authentication-plugin=mysql_native_password
                restart: always
                container_name: mysql_db_ee
                volumes:
                        - db_data:/var/lib/mysql
                environment:
                        MYSQL_DATABASE: expressionengine
                        MYSQL_USER: expressionengine
                        MYSQL_PASSWORD: expressionengine
                        MYSQL_ROOT_PASSWORD: expressionengine
                        MYSQL_HOST: db
                ports:
                        - 3306:3306
                networks:
                        - ee-net
                expose:
                        - 3306

        adminer:
                image: adminer:latest
                container_name: adminer_ee
                restart: always
                ports:
                        - 8181:8080
                networks:
                        - ee-net
                links:
                        - db

        expressionengine:
                build: .
                image: expressionengine:7.2.15
                container_name: expressionengine-7.2.15
                ports:
                        - 7215:80
                volumes:
                        - $PWD/expressionengine:/var/www/html
                depends_on:
                        - db
                links:
                        - db
                networks:
                        - ee-net

volumes:
        db_data:

networks:
        ee-net:
